name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Voer deze workflow uit bij een push naar de main branch

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Debug - Toon huidige bestanden in de repo
        run: ls -la

      - name: Debug - Toon actieve AWS configuratie
        run: aws configure list

      - name: Debug - Toon beschikbare S3 buckets
        run: aws s3 ls

      - name: Upload to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} --delete
